### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by MesameruNayami** [TheRealCatherine/StageMechanic#17]
While attempting to name files within the editor, it continues to accept the keystrokes in editior and interprets the keystroke inputs as naming.

**Comment by TheRealCatherine** [comment]
Need to have InputManager check BlockManager for open file dialogs in initial fix. Should take about 20 minutes to fix.

**Comment by TheRealCatherine** [comment]
Fixed in revision 31f0d1ff0d2bcd1150b63e3be28a44ba741fb7cb

**Comment by TheRealCatherine** [comment]
Also see: https://github.com/GracesGames/SimpleFileBrowser/issues/28
